#!/bin/bash
# run relevant scripts before nginx logs are rotated
# from /usr/alifeee/nginx-user-dashboard/
# this file to be placed in /etc/logrotate.d/httpd-prerotate
# it has no extension as run-parts ignores files with "."

echo "running as $USER"
echo "groups: $(groups)"

# make history CSV
/usr/alifeee/nginx-user-dashboard/log-to-csv.sh

# update HTML file
/usr/alifeee/nginx-user-dashboard/history-to-html.sh
